### ISSUE TITLE
scrapy-athlinks is broken

### ISSUE THREAD

**Issue by josevnz** [aaron-schroeder/athlinks-scraper-scrapy#2]
Hello,

API on related tools has changed quite a bit over 2 years and the project doesn't work out of the box anymore (related to the fact the versions of related tools were not pinned on the requirements.txt file):

## Triggering the error

So installing like this (using a virtual environment):

```shell
python -m venv ~/virtualenv/scrapy-athlinks-test
. ~/virtualenv/scrapy-athlinks-test/bin/activate
git clone https://github.com/aaron-schroeder/athlinks-scraper-scrapy
cd athlinks-scraper-scrapy
pip install -r requirements.txt
```

And then running it:

```shell
(scrapy-athlinks-test) [josevnz@dmaf5 athlinks-scraper-scrapy]$ cd scrapy_athlinks
(scrapy-athlinks-test) [josevnz@dmaf5 scrapy_athlinks]$ scrapy crawl race -a url=https://www.athlinks.com/event/33913/results/Event/1018673 -O out.json
2024-10-13 08:10:35 [scrapy.utils.log] INFO: Scrapy 2.6.2 started (bot: scrapy_athlinks)
2024-10-13 08:10:35 [scrapy.utils.log] INFO: Versions: lxml 5.3.0.0, libxml2 2.12.9, cssselect 1.2.0, parsel 1.9.1, w3lib 2.2.1, Twisted 24.7.0, Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)], pyOpenSSL 24.2.1 (OpenSSL 3.3.2 3 Sep 2024), cryptography 43.0.1, Platform Linux-6.5.12-100.fc37.x86_64-x86_64-with-glibc2.36
2024-10-13 08:10:35 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'scrapy_athlinks',
 'EDITOR': '/usr/bin/nano',
 'NEWSPIDER_MODULE': 'scrapy_athlinks.spiders',
 'SPIDER_MODULES': ['scrapy_athlinks.spiders']}
2024-10-13 08:10:35 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2024-10-13 08:10:35 [scrapy.extensions.telnet] INFO: Telnet Password: e65cab25ae5beefe
2024-10-13 08:10:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2024-10-13 08:10:35 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "http"
Traceback (most recent call last):
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)
            ^^^^^^^^^^^^^^^^^
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
                  ^^^^^^^^^^^^^^^^
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
2024-10-13 08:10:35 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.http.HTTPDownloadHandler" for scheme "https"
Traceback (most recent call last):
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)
            ^^^^^^^^^^^^^^^^^
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
                  ^^^^^^^^^^^^^^^^
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
2024-10-13 08:10:35 [scrapy.core.downloader.handlers] ERROR: Loading "scrapy.core.downloader.handlers.s3.S3DownloadHandler" for scheme "s3"
Traceback (most recent call last):
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/__init__.py", line 49, in _load_handler
    dhcls = load_object(path)
            ^^^^^^^^^^^^^^^^^
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/s3.py", line 1, in <module>
    from scrapy.core.downloader.handlers.http import HTTPDownloadHandler
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http.py", line 2, in <module>
    from scrapy.core.downloader.handlers.http11 import (
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
                  ^^^^^^^^^^^^^^^^
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
Unhandled error in Deferred:
2024-10-13 08:10:35 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/crawler.py", line 205, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/crawler.py", line 209, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/twisted/internet/defer.py", line 2287, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/twisted/internet/defer.py", line 2197, in _cancellableInlineCallbacks
    _inlineCallbacks(None, gen, status, _copy_context())
--- <exception caught here> ---
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/twisted/internet/defer.py", line 2014, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/crawler.py", line 101, in crawl
    self.engine = self._create_engine()
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/crawler.py", line 115, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/engine.py", line 83, in __init__
    self.downloader = downloader_cls(crawler)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/__init__.py", line 83, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/middleware.py", line 59, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/middleware.py", line 40, in from_settings
    mwcls = load_object(clspath)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/downloadermiddlewares/retry.py", line 27, in <module>
    from scrapy.core.downloader.handlers.http11 import TunnelError
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
builtins.AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'

2024-10-13 08:10:35 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/twisted/internet/defer.py", line 2014, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/crawler.py", line 101, in crawl
    self.engine = self._create_engine()
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/crawler.py", line 115, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/engine.py", line 83, in __init__
    self.downloader = downloader_cls(crawler)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/__init__.py", line 83, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/middleware.py", line 59, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/middleware.py", line 40, in from_settings
    mwcls = load_object(clspath)
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/downloadermiddlewares/retry.py", line 27, in <module>
    from scrapy.core.downloader.handlers.http11 import TunnelError
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/handlers/http11.py", line 23, in <module>
    from scrapy.core.downloader.contextfactory import load_context_factory_from_settings
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/contextfactory.py", line 11, in <module>
    from scrapy.core.downloader.tls import DEFAULT_CIPHERS, openssl_methods, ScrapyClientTLSOptions
  File "/home/josevnz/virtualenv/scrapy-athlinks-test/lib64/python3.11/site-packages/scrapy/core/downloader/tls.py", line 23, in <module>
    METHOD_SSLv3: SSL.SSLv3_METHOD,                     # SSL 3 (NOT recommended)
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv3_METHOD'
```

## Workaround

If you downgrade some of the dependencies then the scrapping works again:

```shell
# Down from 24.2.1
pip install pyopenssl==22.0.0
# Down from 43.0.1
pip install cryptography==38.0.4
# Down from 24.7.0
pip install Twisted==22.10.0
```

Then running the crawler again works:

```shell
(scrapy-athlinks-test) [josevnz@dmaf5 scrapy_athlinks]$ scrapy crawl race -a url=https://www.athlinks.com/event/33913/results/Event/1018673 -O out.jso
...
{'downloader/request_bytes': 252737,
 'downloader/request_count': 728,
 'downloader/request_method_count/GET': 728,
 'downloader/response_bytes': 11414740,
 'downloader/response_count': 728,
 'downloader/response_status_count/200': 728,
 'elapsed_time_seconds': 22.823302,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 10, 13, 12, 15, 58, 310784),
 'item_scraped_count': 719,
 'log_count/DEBUG': 1448,
 'log_count/INFO': 11,
 'memusage/max': 78098432,
 'memusage/startup': 78098432,
 'request_depth_max': 9,
 'response_received_count': 728,
 'scheduler/dequeued': 728,
 'scheduler/dequeued/memory': 728,
 'scheduler/enqueued': 728,
 'scheduler/enqueued/memory': 728,
 'start_time': datetime.datetime(2024, 10, 13, 12, 15, 35, 487482)}
2024-10-13 08:15:58 [scrapy.core.engine] INFO: Spider closed (finished)

```

**Comment by josevnz** [comment]
I forked the project here: https://github.com/josevnz/scrapy-athlinks
Will try to do some cleanup and then share my changes with you.

**Comment by josevnz** [comment]
I created a pull request here: https://github.com/aaron-schroeder/scrapy-athlinks/pull/3
